# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
    - test
    - security

variables:
    SECRET_DETECTION_ENABLED: "true"
    GO_VERSION: "1.24-alpine"
    GOLANGCI_LINT_VERSION: "v2.4.0-alpine"

include:
    - template: Security/SAST.gitlab-ci.yml
    - template: Security/Secret-Detection.gitlab-ci.yml

lint:
    stage: test
    image: golangci/golangci-lint:${GOLANGCI_LINT_VERSION}
    before_script:
        - golangci-lint --version
    script:
        - golangci-lint run ./...

unit_tests:
    stage: test
    image: golang:${GO_VERSION}
    before_script:
        - go version
        - go mod download
    script:
        - go test -v ./internal/...
        # - go test -v ./cmd/...
        - go test -v ./pkg/... || true
    coverage: '/coverage: \d+\.\d+% of statements/'
    artifacts:
        reports:
            junit: report.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml
        expire_in: 30 days
    only:
        - merge_requests
        - main
        - dev

integration_tests:
    stage: test
    image: golang:${GO_VERSION}
    before_script:
        - go version
        - go mod download
    script:
        - go test -v ./tests/...
    only:
        - merge_requests

# Override SAST to use security stage
sast:
    stage: security

secret_detection:
    stage: security
