# https://taskfile.dev
version: "3"

tasks:
    openapi:http:
        desc: Generate OpenAPI HTTP files
        cmds:
            - ./scripts/openapi-http.sh registration internal/ports/http registrationhttp
            - ./scripts/openapi-http.sh student internal/ports/http studenthttp

    http:
        cmds:
            - cmd: go run ./cmd/api/
              ignore_error: true
    http:local:
        desc: Run HTTP server with local environment (.env.local)
        dotenv:
            - .env.local
        cmds:
            - cmd: go run ./cmd/api/
              ignore_error: true
    http:dev:
        desc: Run HTTP server with dev environment (.env.dev)
        dotenv:
            - .env.dev
        cmds:
            - cmd: go run ./cmd/api/
              ignore_error: true

    audit:
        desc: Run quality control audit
        cmds:
            - cmd: go mod tidy
            - cmd: go mod verify
            - cmd: go vet ./...
            - cmd: golangci-lint run ./...
            - cmd: gotest ./internal/...
            - cmd: gotest ./pkg/...
            - cmd: gotest ./tests/...

    lint:
        desc: Run linters
        cmds:
            - cmd: golangci-lint run ./...

    test:unit:
        desc: Run unit tests
        cmds:
            - cmd: gotest ./internal/...
            - cmd: gotest ./pkg/...
              ignore_error: true
    test:integration:
        desc: Run integration tests
        cmds:
            - cmd: gotest ./tests/...
              ignore_error: true
    test:
        desc: Run all tests (unit and integration)
        deps: [test:unit, test:integration]

    docker:local:
        desc: Run local Postgres database in Docker
        cmds:
            - cmd: docker run --name ucmsv2-postgres -d -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=ucms -p 8765:5432 postgres:16.8
    compose:infra:up:
        desc: Start infrastructure services using Docker Compose
        aliases:
            - infra:up
        cmds:
            - cmd: docker compose -f compose.yaml --profile infra up -d
    compose:infra:down:
        desc: Stop infrastructure services using Docker Compose
        aliases:
            - infra:down
        cmds:
            - cmd: docker compose -f compose.yaml --profile infra down
    compose:infra:restart:
        desc: Restart infrastructure services using Docker Compose
        aliases:
            - infra:restart
        cmds:
            - cmd: docker compose -f compose.yaml --profile infra restart
