# https://taskfile.dev
version: '3'

vars:

tasks:
  openapi_http:
    cmds:
      - ./scripts/openapi-http.sh registration internal/ports/http registrationhttp
  http:
    cmds:
      - cmd: go run ./cmd/api/
        ignore_error: true
  test_unit:
    cmds:
      - cmd: gotest -v ./internal/...
      - cmd: gotest -v ./pkg/...
        ignore_error: true
  test_integration:
    cmds:
      - cmd: gotest -v ./tests/...
        ignore_error: true
  test:
    deps: [test_unit, test_integration]
