// Package studenthttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package studenthttp

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Barcode defines model for Barcode.
type Barcode = string

// GroupID defines model for GroupID.
type GroupID = openapi_types.UUID

// GetV1StudentsMeParams defines parameters for GetV1StudentsMe.
type GetV1StudentsMeParams struct {
	// Ucmsv2Access access jwt token
	Ucmsv2Access *string `form:"ucmsv2_access,omitempty" json:"ucmsv2_access,omitempty"`
}
