receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318

processors:
    tail_sampling:
        decision_wait: 10s
        num_traces: 100
        expected_new_traces_per_sec: 10
        policies:
            [
                {
                    name: error_policy,
                    type: status_code,
                    status_code: { status_codes: [ERROR, UNSET] },
                },
                {
                    name: latency_policy,
                    type: latency,
                    latency: { threshold_ms: 600, upper_threshold_ms: 10000 },
                },
                {
                    name: probabilistic_policy,
                    type: probabilistic,
                    probabilistic: { sampling_percentage: 10 },
                },
            ]

exporters:
    otlp:
        endpoint: ucmsv2-tempo:4317
        tls:
            insecure: true
    otlphttp/logs:
        endpoint: http://ucmsv2-loki:3100/otlp
        tls:
            insecure: true
    prometheus:
        endpoint: 0.0.0.0:8889
        namespace: default

extensions:
    health_check:
    pprof:
    zpages:

service:
    extensions: [health_check, pprof, zpages]
    telemetry:
        logs:
            level: debug
    pipelines:
        traces:
            receivers: [otlp]
            processors: []
            exporters: [otlp]
        metrics:
            receivers: [otlp]
            processors: []
            exporters: [prometheus]
        logs:
            receivers: [otlp]
            processors: []
            exporters: [otlphttp/logs]
