global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
    # - "first.rules"
    # - "second.rules"

scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets: ["localhost:9090"]

    - job_name: otel-collector
      static_configs:
          - targets: ["ucmsv2-otel-collector:8889"]
