// Package registrationhttp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package registrationhttp

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// PostV1RegistrationStartStudentJSONBody defines parameters for PostV1RegistrationStartStudent.
type PostV1RegistrationStartStudentJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// PostV1RegistrationStartStudentJSONRequestBody defines body for PostV1RegistrationStartStudent for application/json ContentType.
type PostV1RegistrationStartStudentJSONRequestBody PostV1RegistrationStartStudentJSONBody
